---
- name: Configure Ubantu
  hosts: all
  become: true
  roles: 
      - { role: server-config }
- name: Configure Load Balancer
  hosts: balancer
  roles:
      - { role: ansible-role-haproxy } 
- name: Deploy webserver 1 
  hosts: web1
  roles:
      - { role: web1 }
- name: Deploy webserver 2
  hosts: web2
  roles: 
      - { role: web2 }

- name: Tomcat deployment playbook
  hosts: web2       # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
 # become_method: sudo       # Set become method
 # remote_user: root         # Update username for remote server
  vars:
    tomcat_ver: 9.0.30                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: Str0ngManagerP@ssw3rd      # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: Str0ngAdminP@ssw3rd          # UI admin password
  roles:
    - tomcat   
